apiVersion: v1
kind: Secret
metadata:
  name: privateregistrykey
data:
  .dockerconfigjson: ewo # replace with your secret with the base64 encoding of .docker/config.json. More detail can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials
type: kubernetes.io/dockerconfigjson